// src/components/AI/AIPanel.jsx — Tabbed AI: Chat (RAG+Agent) | Git | Models
import { useState, useRef, useEffect, useCallback } from 'react';
import useEditorStore from '../../store/editorStore';
import useProjectIndex from '../../store/projectIndex';
import useRagStore from '../../store/ragStore';
import GitPanel from './GitPanel';
import ModelGuide from './ModelGuide';

const OLLAMA = 'http://localhost:11434';

// ── Helpers ───────────────────────────────────────────────────────────────────

function parseFileEdits(text) {
  const edits = [];
  const re = /FILE:\s*([^\n]+)\n```[a-zA-Z0-9_-]*\n([\s\S]*?)```/g;
  let m;
  while ((m = re.exec(text)) !== null)
    edits.push({ filePath: m[1].trim(), content: m[2].replace(/\n$/, '') });
  return edits;
}

function isRunRequest(text) {
  return /\b(run|start|launch|execute)\b[\s\S]*\b(project|app|server|this)\b/i.test(text)
    || /^run this project$/i.test(text.trim());
}

function isKnapsackJsRequest(text) {
  const lower = (text || '').toLowerCase();
  const hasKnapsack = lower.includes('knapsack') || lower.includes('kanpsack') || lower.includes('knap sack');
  const hasJs =
    lower.includes('javascript') ||
    lower.includes('javaacript') ||
    lower.includes('java script') ||
    /\bjs\b/.test(lower);
  const wantsCode = lower.includes('code') || lower.includes('teach') || lower.includes('algorithm');
  return hasKnapsack && hasJs && wantsCode;
}

function knapsackJsAutoReply() {
  return [
    '0/1 Knapsack in JavaScript',
    '',
    'Idea:',
    '- You have items with weight and value.',
    '- Choose each item at most once.',
    '- Maximize total value without exceeding capacity.',
    '',
    'Dynamic Programming (1D optimized):',
    '```javascript',
    'function knapsack01(weights, values, capacity) {',
    '  const n = weights.length;',
    '  const dp = new Array(capacity + 1).fill(0);',
    '',
    '  for (let i = 0; i < n; i++) {',
    '    const w = weights[i];',
    '    const v = values[i];',
    '',
    '    // Go backwards so each item is used at most once',
    '    for (let c = capacity; c >= w; c--) {',
    '      dp[c] = Math.max(dp[c], dp[c - w] + v);',
    '    }',
    '  }',
    '',
    '  return dp[capacity];',
    '}',
    '',
    '// Example',
    'const weights = [2, 3, 4, 5];',
    'const values = [3, 4, 5, 8];',
    'const capacity = 8;',
    '',
    'console.log(knapsack01(weights, values, capacity)); // 12',
    '```',
    '',
    'Complexity:',
    '- Time: O(n * capacity)',
    '- Space: O(capacity)',
    '',
    'This answer is auto-generated by rule in the app for knapsack + javascript prompts.',
  ].join('\n');
}

function detectCreateFileTask(text) {
  const raw = (text || '').trim();
  const lower = raw.toLowerCase();
  const asksCreate = lower.includes('create') || lower.includes('make') || lower.includes('genraate');
  const asksFile = lower.includes('file');
  const asksRun = lower.includes('run') || lower.includes('execute');
  if (!asksCreate || !asksFile) return null;

  const isFibonacci =
    lower.includes('fibonacci') ||
    lower.includes('fibanocci') ||
    lower.includes('fibanaci') ||
    lower.includes('fabonacci');
  const isBinarySearch =
    lower.includes('binary search') ||
    lower.includes('binarry search') ||
    lower.includes('binarysearch');
  const isKnapsack =
    lower.includes('knapsack') ||
    lower.includes('kanpsack') ||
    lower.includes('knap sack');

  if (!isFibonacci && !isBinarySearch && !isKnapsack) return null;

  const wantsPython = /\bpython\b|\bpy\b/.test(lower);
  const wantsJs =
    lower.includes('javascript') ||
    lower.includes('javaacript') ||
    lower.includes('java script') ||
    /\bjs\b/.test(lower);

  const language = wantsPython ? 'python' : (wantsJs ? 'javascript' : 'javascript');

  const namedMatch = raw.match(/(?:named|called)\s+([a-zA-Z0-9_.-]+)/i);
  let fileName = namedMatch?.[1] || '';
  const algo = isFibonacci ? 'fibonacci' : (isBinarySearch ? 'binary-search' : 'knapsack');
  if (!fileName) fileName = language === 'python' ? `${algo}.py` : `${algo}.js`;
  if (!fileName.includes('.')) fileName += language === 'python' ? '.py' : '.js';

  const runCommand = language === 'python' ? `python ${fileName}` : `node ${fileName}`;
  return {
    type: isFibonacci ? 'fibonacci' : (isBinarySearch ? 'binary-search' : 'knapsack'),
    language,
    fileName,
    runCommand,
    shouldRun: asksRun,
  };
}

function createTemplate(type, language) {
  if (type === 'binary-search') {
    if (language === 'python') {
      return [
        'def binary_search(arr, target):',
        '    low, high = 0, len(arr) - 1',
        '    while low <= high:',
        '        mid = (low + high) // 2',
        '        if arr[mid] == target:',
        '            return mid',
        '        if arr[mid] < target:',
        '            low = mid + 1',
        '        else:',
        '            high = mid - 1',
        '    return -1',
        '',
        'if __name__ == "__main__":',
        '    nums = [2, 4, 7, 11, 19, 25]',
        '    target = 11',
        '    print(f"Index: {binary_search(nums, target)}")',
      ].join('\n');
    }

    return [
      'function binarySearch(arr, target) {',
      '  let low = 0;',
      '  let high = arr.length - 1;',
      '',
      '  while (low <= high) {',
      '    const mid = Math.floor((low + high) / 2);',
      '    if (arr[mid] === target) return mid;',
      '    if (arr[mid] < target) low = mid + 1;',
      '    else high = mid - 1;',
      '  }',
      '',
      '  return -1;',
      '}',
      '',
      'const nums = [2, 4, 7, 11, 19, 25];',
      'const target = 11;',
      'console.log(`Index: ${binarySearch(nums, target)}`);',
    ].join('\n');
  }

  if (type === 'knapsack') {
    if (language === 'python') {
      return [
        'def knapsack01(weights, values, capacity):',
        '    dp = [0] * (capacity + 1)',
        '    for i in range(len(weights)):',
        '        w, v = weights[i], values[i]',
        '        for c in range(capacity, w - 1, -1):',
        '            dp[c] = max(dp[c], dp[c - w] + v)',
        '    return dp[capacity]',
        '',
        'if __name__ == "__main__":',
        '    weights = [2, 3, 4, 5]',
        '    values = [3, 4, 5, 8]',
        '    capacity = 8',
        '    print(knapsack01(weights, values, capacity))',
      ].join('\n');
    }

    return [
      'function knapsack01(weights, values, capacity) {',
      '  const dp = new Array(capacity + 1).fill(0);',
      '  for (let i = 0; i < weights.length; i++) {',
      '    const w = weights[i];',
      '    const v = values[i];',
      '    for (let c = capacity; c >= w; c--) {',
      '      dp[c] = Math.max(dp[c], dp[c - w] + v);',
      '    }',
      '  }',
      '  return dp[capacity];',
      '}',
      '',
      'const weights = [2, 3, 4, 5];',
      'const values = [3, 4, 5, 8];',
      'const capacity = 8;',
      'console.log(knapsack01(weights, values, capacity));',
    ].join('\n');
  }

  if (language === 'python') {
    return [
      'def fibonacci(n):',
      '    if n <= 1:',
      '        return n',
      '    a, b = 0, 1',
      '    for _ in range(2, n + 1):',
      '        a, b = b, a + b',
      '    return b',
      '',
      'if __name__ == "__main__":',
      '    n = 10',
      '    print(f"Fibonacci({n}) = {fibonacci(n)}")',
    ].join('\n');
  }

  return [
    'function fibonacci(n) {',
    '  if (n <= 1) return n;',
    '  let a = 0;',
    '  let b = 1;',
    '  for (let i = 2; i <= n; i++) {',
    '    const next = a + b;',
    '    a = b;',
    '    b = next;',
    '  }',
    '  return b;',
    '}',
    '',
    'const n = 10;',
    'console.log(`Fibonacci(${n}) = ${fibonacci(n)}`);',
  ].join('\n');
}

// ── Sub-components ────────────────────────────────────────────────────────────

function SearchResults({ results }) {
  const navigateTo = useEditorStore(s => s.navigateTo);
  if (!results || results.length === 0) return null;
  return (
    <div className="mt-2 border border-[#30363d] rounded-lg overflow-hidden bg-[#0d1117]">
      <div className="px-3 py-1.5 text-[10px] uppercase tracking-wide text-[#8b949e] border-b border-[#30363d]">
        Project matches
      </div>
      {results.slice(0, 5).map((r, i) => (
        <button
          key={`${r.path}:${r.line || 1}:${i}`}
          onClick={() => navigateTo(r.path, r.line || 1)}
          className="w-full text-left px-3 py-2 hover:bg-[#21262d] border-b border-[#21262d] last:border-b-0 transition-colors"
        >
          <div className="flex items-center gap-2 min-w-0">
            <span className="text-[#a78bfa] text-xs flex-shrink-0">
              {r.kind === 'symbol' ? 'ƒ' : 'file'}
            </span>
            <span className="text-xs text-[#e6edf3] truncate">{r.name || r.relativePath}</span>
            {r.line && (
              <span className="text-[10px] text-[#484f58] flex-shrink-0">L{r.line}</span>
            )}
          </div>
          <div className="text-[10px] text-[#8b949e] truncate mt-0.5">{r.relativePath}</div>
        </button>
      ))}
    </div>
  );
}

// Count changed lines between two content strings
function countDiff(oldContent, newContent) {
  const oldLines = (oldContent || '').split('\n');
  const newLines = (newContent || '').split('\n');
  const oldSet = new Set(oldLines);
  const newSet = new Set(newLines);
  return {
    added:   newLines.filter(l => !oldSet.has(l)).length,
    removed: oldLines.filter(l => !newSet.has(l)).length,
  };
}

function FilesChangedBar({ edits, onUndo, onKeep }) {
  const [expanded, setExpanded] = useState(false);
  const [undoing,  setUndoing]  = useState(false);
  if (!edits || !edits.length) return null;

  const totalAdded   = edits.reduce((s, e) => s + (e.linesAdded   || 0), 0);
  const totalRemoved = edits.reduce((s, e) => s + (e.linesRemoved || 0), 0);

  const handleUndo = async () => {
    setUndoing(true);
    await onUndo();
    setUndoing(false);
  };

  return (
    <div className="mt-3 border border-[#30363d] rounded-lg overflow-hidden text-xs">
      {/* Header row */}
      <div className="flex items-center gap-2 px-3 py-2 bg-[#161b22]">
        <button
          onClick={() => setExpanded(v => !v)}
          className="flex items-center gap-1.5 text-[#8b949e] hover:text-[#e6edf3] transition-colors"
        >
          <span className="text-[9px]">{expanded ? '▼' : '▶'}</span>
          <span className="font-medium text-[#e6edf3]">
            {edits.length} file{edits.length !== 1 ? 's' : ''} changed
          </span>
          {totalAdded   > 0 && <span className="text-[#3fb950] font-bold">+{totalAdded}</span>}
          {totalRemoved > 0 && <span className="text-[#f85149] font-bold">-{totalRemoved}</span>}
        </button>
        <div className="flex-1" />
        <button
          onClick={onKeep}
          className="px-2.5 py-1 bg-[#238636] hover:bg-[#2ea043] text-white rounded font-semibold transition-colors"
        >
          Keep
        </button>
        <button
          onClick={handleUndo}
          disabled={undoing}
          className="px-2.5 py-1 bg-[#21262d] hover:bg-[#30363d] text-[#8b949e] hover:text-[#e6edf3] rounded border border-[#30363d] font-semibold transition-colors disabled:opacity-50"
        >
          {undoing ? '↩…' : 'Undo'}
        </button>
      </div>

      {/* Expanded file list */}
      {expanded && (
        <div className="border-t border-[#30363d] bg-[#0d1117]">
          {edits.map((e, i) => {
            const parts = e.filePath.replace(/\\/g, '/').split('/');
            const name  = parts.pop();
            const dir   = parts.join('/');
            return (
              <div
                key={i}
                className="flex items-center gap-2 px-3 py-1.5 border-b border-[#21262d] last:border-b-0 hover:bg-[#161b22] transition-colors"
              >
                <span className="text-[#7c3aed]">⊕</span>
                <span className="text-[#e6edf3] font-medium">{name}</span>
                {dir && <span className="text-[#484f58] truncate flex-1 text-[10px]">{dir}</span>}
                <span className="text-[#3fb950] ml-auto">+{e.linesAdded   || 0}</span>
                <span className="text-[#f85149] ml-1">-{e.linesRemoved || 0}</span>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function ChatMessage({ msg, onUndo, onKeep }) {
  const isUser = msg.role === 'user';
  // Strip FILE: code blocks from visible text — they've already been applied
  const visibleContent = (msg.appliedEdits?.length > 0 || msg.kept || msg.undone)
    ? (msg.content || '').replace(/FILE:[ \t]*[^\n]+\n```[\s\S]*?```/g, '').trim()
    : (msg.content || '');

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-3`}>
      <div
        className={`max-w-[92%] rounded-xl px-3 py-2 text-sm break-words leading-relaxed
          ${isUser
            ? 'bg-[#7c3aed] text-white rounded-br-sm'
            : 'bg-[#21262d] text-[#e6edf3] rounded-bl-sm'}`}
      >
        {msg.role === 'assistant' && msg.loading ? (
          <span className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-[#8b949e] animate-bounce" />
            <span className="w-1.5 h-1.5 rounded-full bg-[#8b949e] animate-bounce [animation-delay:0.15s]" />
            <span className="w-1.5 h-1.5 rounded-full bg-[#8b949e] animate-bounce [animation-delay:0.3s]" />
          </span>
        ) : (
          <pre className="whitespace-pre-wrap font-sans text-sm">{visibleContent}</pre>
        )}
        {!isUser && <SearchResults results={msg.searchResults} />}
        {!isUser && msg.appliedEdits?.length > 0 && (
          <FilesChangedBar edits={msg.appliedEdits} onUndo={onUndo} onKeep={onKeep} />
        )}
        {!isUser && msg.undone && (
          <div className="mt-2 text-[11px] text-[#8b949e] italic">↩ Changes reverted</div>
        )}
        {!isUser && msg.kept && (
          <div className="mt-2 text-[11px] text-[#3fb950] italic">✓ Changes kept</div>
        )}
      </div>
    </div>
  );
}

function AgentStep({ step }) {
  const COLORS = {
    READ:  '#79c0ff',
    WRITE: '#3fb950',
    RUN:   '#e3b341',
    DONE:  '#a78bfa',
    ERROR: '#f85149',
  };
  return (
    <div className="flex items-start gap-2 px-3 py-1.5 bg-[#161b22] border border-[#30363d] rounded-lg text-xs font-mono my-1">
      <span style={{ color: COLORS[step.type] || '#8b949e' }} className="flex-shrink-0 font-bold">
        [{step.type}]
      </span>
      <span className="text-[#8b949e] truncate">{step.detail}</span>
    </div>
  );
}

// ── Main panel ────────────────────────────────────────────────────────────────

export default function AIPanel() {
  const {
    tabs, activeTabId,
    selectedModel, ollamaModels, ollamaOnline,
    setSelectedModel,
    showTerminal, toggleTerminal,
    terminalSender,
    detectAndRun,
    pendingAIQuery, pendingAITab,
    setAIQuery, clearAIQuery,
    toast,
    currentFolder,
  } = useEditorStore();

  const {
    semanticSearch,
    getSummary,
    getContextForQuery,
    getProjectTree,
  } = useProjectIndex();

  const {
    search:    ragSearch,
    getContext: ragGetContext,
    buildIndex: buildRagIndex,
    building:  ragBuilding,
    progress:  ragProgress,
    chunks,
    embedModelAvailable,
  } = useRagStore();

  const [tab,        setTab]        = useState('chat');
  const [messages,   setMessages]   = useState([]);
  const [input,      setInput]      = useState('');
  const [streaming,  setStreaming]   = useState(false);
  const [agentMode,  setAgentMode]  = useState(false);
  const [agentSteps, setAgentSteps] = useState([]);

  const bottomRef = useRef(null);
  const inputRef  = useRef(null);
  const abortRef  = useRef(null);

  const activeTab = tabs.find(t => t.id === activeTabId);

  // Auto-scroll
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, agentSteps]);

  // Handle pendingAIQuery from CodeEditor selection → AI panel
  useEffect(() => {
    if (!pendingAIQuery) return;
    if (pendingAIQuery === '\x00git-tab-switch') {
      setTab('git');
      clearAIQuery();
      return;
    }
    const q = pendingAIQuery;
    const t = pendingAITab || 'chat';
    clearAIQuery();
    setTab(t);
    if (t === 'chat') sendMessage(q);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingAIQuery]);

  // ── State helpers ─────────────────────────────────────────────────────────

  const addMsg = (role, content, extra = {}) =>
    setMessages(prev => [...prev, { id: Date.now() + Math.random(), role, content, loading: false, ...extra }]);

  const updateLastAssistant = (content, extra = {}) =>
    setMessages(prev => {
      const next = [...prev];
      for (let i = next.length - 1; i >= 0; i--) {
        if (next[i].role === 'assistant') {
          next[i] = { ...next[i], content, loading: false, ...extra };
          break;
        }
      }
      return next;
    });

  // ── Context builder (RAG → keyword fallback) ──────────────────────────────

  const buildContext = useCallback(async (query) => {
    if (embedModelAvailable && chunks.length > 0) {
      try {
        const ctx = await ragGetContext(query, 5);
        if (ctx) return ctx;
      } catch { /* fall through */ }
    }
    try {
      return await getContextForQuery(query);
    } catch { return ''; }
  }, [embedModelAvailable, chunks, ragGetContext, getContextForQuery]);

  // ── Chat send ─────────────────────────────────────────────────────────────

  const sendMessage = useCallback(async (text) => {
    const userText = (text || input).trim();
    if (!userText || streaming) return;
    setInput('');

    const searchResults = semanticSearch ? semanticSearch(userText, 4) : [];
    addMsg('user', userText, { searchResults });
    addMsg('assistant', '', { loading: true });
    setStreaming(true);

    if (isRunRequest(userText)) {
      detectAndRun();
      updateLastAssistant('Running project — check the terminal.', {});
      setStreaming(false);
      return;
    }

    const createFileTask = detectCreateFileTask(userText);
    if (createFileTask) {
      try {
        const state = useEditorStore.getState();
        const {
          currentFolder,
          setCurrentFolder,
          applyFileEdit,
          showTerminal,
          toggleTerminal,
          terminalSender,
          toast,
        } = state;

        let targetFolder = currentFolder;
        if (!targetFolder && window.api?.openFolder) {
          const picked = await window.api.openFolder();
          const selected = picked?.filePaths?.[0];
          if (selected) {
            setCurrentFolder(selected);
            targetFolder = selected;
          }
        }

        if (!targetFolder) {
          updateLastAssistant('Folder not selected, so file creation was skipped.', {});
          setStreaming(false);
          return;
        }

        const code = createTemplate(createFileTask.type, createFileTask.language);
        const ok = await applyFileEdit(createFileTask.fileName, code);
        if (!ok) {
          updateLastAssistant(`Could not create ${createFileTask.fileName}.`, {});
          setStreaming(false);
          return;
        }

        if (createFileTask.shouldRun) {
          if (!showTerminal) toggleTerminal();

          const sendRun = () => {
            const sender = terminalSender || useEditorStore.getState().terminalSender;
            if (sender) {
              sender(`cd \"${targetFolder}\" && ${createFileTask.runCommand}\r`);
              toast(`Running: ${createFileTask.runCommand}`, 'success');
            } else {
              setTimeout(sendRun, 250);
            }
          };
          setTimeout(sendRun, 300);
          updateLastAssistant(
            `Created ${createFileTask.fileName} in editor and started ${createFileTask.runCommand} in terminal.`,
            {},
          );
        } else {
          updateLastAssistant(`Created ${createFileTask.fileName} in editor.`, {});
        }
      } catch (err) {
        updateLastAssistant(`Task failed: ${err.message}`, {});
      }
      setStreaming(false);
      return;
    }

    if (isKnapsackJsRequest(userText)) {
      updateLastAssistant(knapsackJsAutoReply(), {});
      setStreaming(false);
      return;
    }

    try {
      const ragCtx  = await buildContext(userText);
      const summary = getSummary ? getSummary() : '';
      const tree    = getProjectTree ? getProjectTree() : '';

      const systemPrompt = [
        'You are an expert AI coding assistant embedded in a code editor.',
        'Be concise and technically precise.',
        summary ? `\nPROJECT:\n${summary}` : '',
        tree    ? `\nFILE TREE:\n${tree.slice(0, 1500)}` : '',
        ragCtx  ? `\nRELEVANT CODE:\n${ragCtx}` : '',
        activeTab
          ? `\nACTIVE FILE (${activeTab.name}):\n\`\`\`${activeTab.language || ''}\n${activeTab.content?.slice(0, 3000) || ''}\n\`\`\``
          : '',
        '',
        '## CRITICAL RULE: ALWAYS EDIT FILES DIRECTLY',
        'When asked to change ANYTHING in the code (colors, text, logic, styles, components), you MUST output the COMPLETE modified file content.',
        'NEVER just describe what to change. NEVER say "change X to Y". ALWAYS output the actual changed file.',
        'Use this exact format for EVERY file you change:',
        'FILE: relative/path/to/file.ext',
        '```lang',
        '// COMPLETE file content with your change already applied',
        '```',
        'Output ALL files that need editing. No partial snippets. Full file every time.',
      ].filter(Boolean).join('\n');

      const historyMsgs = messages
        .filter(m => !m.loading)
        .slice(-10)
        .map(m => ({ role: m.role, content: m.content }));

      const res = await fetch(`${OLLAMA}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal: (abortRef.current = new AbortController()).signal,
        body: JSON.stringify({
          model: selectedModel || 'codellama',
          stream: true,
          messages: [
            { role: 'system', content: systemPrompt },
            ...historyMsgs,
            { role: 'user', content: userText },
          ],
        }),
      });

      if (!res.ok) throw new Error(`Ollama ${res.status}`);

      let full = '';
      const reader = res.body.getReader();
      const dec    = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        for (const line of dec.decode(value).split('\n')) {
          if (!line.trim()) continue;
          try {
            const j = JSON.parse(line);
            if (j.message?.content) { full += j.message.content; updateLastAssistant(full); }
          } catch { /* partial JSON line */ }
        }
      }

      // ── Auto-apply all FILE: edits found in the response ──────────────
      const edits = parseFileEdits(full);
      const applied = [];
      if (edits.length > 0) {
        const { tabs: currTabs, applyFileEdit } = useEditorStore.getState();
        for (const edit of edits) {
          const existing = currTabs.find(
            t => t.path?.endsWith(edit.filePath) || t.path === edit.filePath
          );
          const oldContent = existing?.content ?? '';
          await applyFileEdit(edit.filePath, edit.content);
          const { added, removed } = countDiff(oldContent, edit.content);
          applied.push({
            filePath:     edit.filePath,
            oldContent,
            newContent:   edit.content,
            linesAdded:   added,
            linesRemoved: removed,
          });
        }
      }
      updateLastAssistant(full, { fileEdits: edits, appliedEdits: applied });
    } catch (err) {
      if (err.name !== 'AbortError')
        updateLastAssistant(`Error: ${err.message}`, {});
    } finally {
      setStreaming(false);
      abortRef.current = null;
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [input, streaming, messages, selectedModel, activeTab, buildContext,
      semanticSearch, getSummary, getProjectTree, detectAndRun]);

  // ── Agentic send (Cline-style) ────────────────────────────────────────────

  const runAgent = useCallback(async (task) => {
    if (!task.trim() || streaming) return;
    setInput('');
    setAgentSteps([]);
    addMsg('user', `[Agent] ${task}`);
    addMsg('assistant', '', { loading: true });
    setStreaming(true);

    const addStep = (type, detail) =>
      setAgentSteps(prev => [...prev, { type, detail, id: Date.now() + Math.random() }]);

    try {
      const ragCtx  = await buildContext(task);
      const summary = getSummary?.() || '';
      const tree    = getProjectTree?.() || '';

      const AGENT_SYSTEM = [
        'You are an autonomous coding agent. Solve tasks step-by-step using tool calls.',
        'TOOLS (one per line, use exact format):',
        'READ: path/to/file',
        'WRITE: path/to/file',
        '(content on following lines until next tool or DONE)',
        'RUN: shell command',
        'DONE: brief summary',
        '',
        'Rules: READ before WRITE. Keep changes minimal. After RUN, describe what to check.',
        summary ? `\nProject: ${summary}` : '',
        ragCtx  ? `\nContext:\n${ragCtx}` : '',
        tree    ? `\nTree:\n${tree.slice(0, 1000)}` : '',
      ].filter(Boolean).join('\n');

      const agentMsgs = [
        { role: 'system', content: AGENT_SYSTEM },
        { role: 'user',   content: task },
      ];

      let fullLog = '';
      const MAX_TURNS = 8;

      for (let turn = 0; turn < MAX_TURNS; turn++) {
        const res = await fetch(`${OLLAMA}/api/chat`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: (abortRef.current = new AbortController()).signal,
          body: JSON.stringify({
            model: selectedModel || 'codellama',
            stream: false,
            messages: agentMsgs,
          }),
        });
        if (!res.ok) throw new Error(`Ollama ${res.status}`);

        const data  = await res.json();
        const reply = data.message?.content || '';
        agentMsgs.push({ role: 'assistant', content: reply });

        let toolResult = '';
        let done = false;
      const agentApplied = [];
        for (let li = 0; li < lines.length; li++) {
          const line = lines[li].trim();

          if (line.startsWith('READ:')) {
            const fp = line.slice(5).trim();
            addStep('READ', fp);
            if (window.api) {
              const fullPath = fp.startsWith('/') ? fp : `${currentFolder}/${fp}`;
              const r = await window.api.readFile(fullPath);
              toolResult += `\nFILE ${fp}:\n${r.content || r.error || '(empty)'}\n`;
            }

          } else if (line.startsWith('WRITE:')) {
            const fp = line.slice(6).trim();
            addStep('WRITE', fp);
            // Collect content lines until next tool keyword or end
            const contentLines = [];
            li++;
            while (li < lines.length) {
              const next = lines[li].trim();
              if (next.startsWith('READ:') || next.startsWith('WRITE:') ||
                  next.startsWith('RUN:')  || next.startsWith('DONE:')) {
                li--;
                break;
              }
              contentLines.push(lines[li]);
              li++;
            }
            if (window.api) {
              const fullPath = fp.startsWith('/') ? fp : `${currentFolder}/${fp}`;
              // Capture old content for undo
              const { tabs: currTabs, applyFileEdit } = useEditorStore.getState();
              const existing   = currTabs.find(t => t.path === fullPath || t.path?.endsWith(fp));
              const oldContent = existing?.content ?? '';
              const newContent = contentLines.join('\n');
              await applyFileEdit(fp, newContent);
              const { added, removed } = countDiff(oldContent, newContent);
              agentApplied.push({ filePath: fp, oldContent, newContent, linesAdded: added, linesRemoved: removed });
              toolResult += `\nWrote: ${fp}\n`;
            }

          } else if (line.startsWith('RUN:')) {
            const cmd = line.slice(4).trim();
            addStep('RUN', cmd);
            if (!showTerminal) toggleTerminal();
            setTimeout(() => {
              const sender = terminalSender || useEditorStore.getState().terminalSender;
              if (sender) sender(cmd + '\r');
            }, 500);
            toolResult += `\nRan: ${cmd} (check terminal)\n`;

          } else if (line.startsWith('DONE:')) {
            const summary = line.slice(5).trim();
            addStep('DONE', summary);
            fullLog += `\n✅ ${summary}`;
            done = true;
            break;
          }
        }

        fullLog += `\n${reply}`;
        updateLastAssistant(fullLog.trim());

        if (done) break;

        if (toolResult) {
          agentMsgs.push({ role: 'user', content: `Tool results:${toolResult}` });
        } else {
          break; // natural reply with no tools
        }
      }

      updateLastAssistant(fullLog.trim(), { fileEdits: parseFileEdits(fullLog), appliedEdits: agentApplied });
    } catch (err) {
      if (err.name !== 'AbortError')
        updateLastAssistant(`Agent error: ${err.message}`, {});
    } finally {
      setStreaming(false);
      abortRef.current = null;
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [input, streaming, selectedModel, buildContext, getSummary, getProjectTree,
      currentFolder, showTerminal, toggleTerminal, terminalSender]);

  // ── Edit undo / keep ──────────────────────────────────────────────────────

  const updateMessage = useCallback((id, updates) =>
    setMessages(prev => prev.map(m => m.id === id ? { ...m, ...updates } : m)),
  []);

  const handleUndoEdits = useCallback(async (msgId, edits) => {
    const { applyFileEdit } = useEditorStore.getState();
    for (const edit of [...edits].reverse()) {
      if (edit.oldContent !== undefined) {
        await applyFileEdit(edit.filePath, edit.oldContent);
      }
    }
    updateMessage(msgId, { appliedEdits: [], undone: true });
  }, [updateMessage]);

  const handleKeepEdits = useCallback((msgId) => {
    updateMessage(msgId, { appliedEdits: [], kept: true });
  }, [updateMessage]);

  // ── Handlers ──────────────────────────────────────────────────────────────

  const handleSend = () => agentMode ? runAgent(input) : sendMessage(input);
  const handleStop = () => abortRef.current?.abort();
  const handleKey  = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); }
  };

  // ── Build RAG index ────────────────────────────────────────────────────────

  const buildRag = async () => {
    if (!currentFolder || !window.api) { toast('Open a folder first', 'warn'); return; }
    toast('Building RAG index…', 'info');
    const res = await window.api.readDirRecursive(currentFolder, { content: true });
    if (res.files) {
      await buildRagIndex(res.files, currentFolder);
      toast(`RAG ready — ${chunks.length} chunks`, 'success');
    }
  };

  // ── Quick actions ──────────────────────────────────────────────────────────

  const QUICK = [
    { label: '🔍 Analyze project',  text: 'Analyze this project: architecture, main files, entry points, key patterns.' },
    { label: '▶ Run project',       text: 'Run this project' },
    { label: '🐛 Find bugs',        text: 'Review the active file for bugs, security issues, and improvements.' },
    { label: '📝 Write tests',      text: 'Write unit tests for the active file.' },
    { label: '✨ Refactor',         text: 'Refactor the active file for clarity and best practices.' },
    { label: '📖 Explain code',     text: 'Explain what the active file does in plain English.' },
  ];

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col h-full overflow-hidden">

      {/* ── Tab bar ───────────────────────────────────────────────────────── */}
      <div className="flex items-center border-b border-[#30363d] bg-[#161b22] flex-shrink-0">
        {[
          { id: 'chat',   label: '🤖 Chat'   },
          { id: 'git',    label: '🌿 Git'    },
          { id: 'models', label: '📦 Models' },
        ].map(t => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`px-3 py-2 text-xs font-medium transition-colors flex-1 border-b-2
              ${tab === t.id
                ? 'border-[#7c3aed] text-[#e6edf3]'
                : 'border-transparent text-[#8b949e] hover:text-[#e6edf3]'}`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Git tab ───────────────────────────────────────────────────────── */}
      {tab === 'git' && (
        <div className="flex-1 overflow-y-auto">
          <GitPanel />
        </div>
      )}

      {/* ── Models tab ────────────────────────────────────────────────────── */}
      {tab === 'models' && (
        <div className="flex-1 overflow-y-auto">
          <ModelGuide />
        </div>
      )}

      {/* ── Chat tab ──────────────────────────────────────────────────────── */}
      {tab === 'chat' && (
        <>
          {/* Model selector + agent toggle */}
          <div className="flex items-center gap-1 px-2 py-1.5 border-b border-[#30363d] flex-shrink-0 bg-[#0d1117]">
            <select
              value={selectedModel}
              onChange={e => setSelectedModel(e.target.value)}
              className="flex-1 bg-[#21262d] border border-[#30363d] rounded px-2 py-1 text-xs text-[#e6edf3] focus:outline-none focus:border-[#7c3aed] min-w-0"
            >
              {ollamaModels.length > 0
                ? ollamaModels.map(m => <option key={m} value={m}>{m}</option>)
                : <option value={selectedModel}>{selectedModel}</option>}
            </select>

            <button
              onClick={() => setAgentMode(v => !v)}
              title={agentMode ? 'Switch to Chat mode' : 'Switch to Agent mode (reads/writes files)'}
              className={`px-2 py-1 rounded text-[10px] font-semibold transition-colors flex-shrink-0
                ${agentMode
                  ? 'bg-[#f0883e] text-white'
                  : 'bg-[#21262d] text-[#8b949e] hover:text-[#e6edf3] border border-[#30363d]'}`}
            >
              {agentMode ? '🤖 Agent' : '💬 Chat'}
            </button>

            <div
              className={`w-2 h-2 rounded-full flex-shrink-0 ${ollamaOnline ? 'bg-[#3fb950]' : 'bg-[#f85149]'}`}
              title={ollamaOnline ? 'Ollama online' : 'Ollama offline — run: ollama serve'}
            />
          </div>

          {/* Message list */}
          <div className="flex-1 overflow-y-auto px-3 py-3">
            {messages.length === 0 && (
              <div className="text-center py-8">
                <div className="text-4xl mb-3">🤖</div>
                <p className="text-[#8b949e] text-sm mb-1">
                  {agentMode
                    ? 'Agent mode — I can read/write files and run commands'
                    : 'Ask anything about your code'}
                </p>
                <p className="text-[#484f58] text-xs">
                  {ollamaOnline
                    ? `${selectedModel} · ${embedModelAvailable ? `RAG ${chunks.length > 0 ? `(${chunks.length} chunks)` : '(not indexed)'}` : 'keyword search'}`
                    : 'Ollama offline — start with: ollama serve'}
                </p>
              </div>
            )}

            {messages.map(msg => (
              <ChatMessage
                key={msg.id}
                msg={msg}
                onUndo={() => handleUndoEdits(msg.id, msg.appliedEdits || [])}
                onKeep={() => handleKeepEdits(msg.id)}
              />
            ))}

            {agentSteps.length > 0 && (
              <div className="mt-2 space-y-1">
                {agentSteps.map(s => <AgentStep key={s.id} step={s} />)}
              </div>
            )}

            <div ref={bottomRef} />
          </div>

          {/* Quick actions (shown only when no messages) */}
          {messages.length === 0 && (
            <div className="px-2 pb-2 flex-shrink-0">
              <div className="grid grid-cols-2 gap-1">
                {QUICK.map(q => (
                  <button
                    key={q.label}
                    onClick={() => sendMessage(q.text)}
                    className="px-2 py-1.5 bg-[#21262d] hover:bg-[#30363d] border border-[#30363d] rounded text-[10px] text-[#8b949e] hover:text-[#e6edf3] text-left transition-colors truncate"
                  >
                    {q.label}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* RAG status bar */}
          <div className="px-3 py-1.5 border-t border-[#30363d] bg-[#0d1117] flex items-center gap-2 text-[10px] flex-shrink-0">
            {embedModelAvailable ? (
              ragBuilding ? (
                <span className="text-[#e3b341] animate-pulse flex items-center gap-1">
                  <span>⚡ Building RAG…</span>
                  <span>{ragProgress}%</span>
                  <div className="flex-1 h-1 bg-[#21262d] rounded overflow-hidden ml-1">
                    <div className="h-full bg-[#e3b341] transition-all" style={{ width: `${ragProgress}%` }} />
                  </div>
                </span>
              ) : chunks.length > 0 ? (
                <span className="text-[#3fb950]">⚡ RAG: {chunks.length} chunks</span>
              ) : (
                <button
                  onClick={buildRag}
                  className="text-[#f0883e] hover:text-[#e3b341] transition-colors"
                >
                  ⚡ Build RAG index
                </button>
              )
            ) : (
              <span className="text-[#484f58]">
                RAG unavailable —{' '}
                <code className="bg-[#161b22] px-1 rounded">ollama pull nomic-embed-text</code>
              </span>
            )}
          </div>

          {/* Input */}
          <div className="px-2 pb-2 pt-1 flex-shrink-0 border-t border-[#30363d]">
            <div className="flex gap-1 items-end">
              <textarea
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={handleKey}
                placeholder={
                  agentMode
                    ? 'Describe a task — agent reads/writes files autonomously…'
                    : 'Ask about your code… (Enter to send, Shift+Enter for newline)'
                }
                rows={2}
                className="flex-1 bg-[#21262d] border border-[#30363d] rounded-lg px-3 py-2 text-sm text-[#e6edf3] placeholder-[#484f58] resize-none focus:outline-none focus:border-[#7c3aed] leading-relaxed"
              />
              <button
                onClick={streaming ? handleStop : handleSend}
                disabled={!streaming && !input.trim()}
                className={`px-3 py-2 rounded-lg text-sm font-medium transition-colors flex-shrink-0 self-end
                  ${streaming
                    ? 'bg-[#f85149] hover:bg-[#da3633] text-white'
                    : input.trim()
                      ? 'bg-[#7c3aed] hover:bg-[#6d28d9] text-white'
                      : 'bg-[#21262d] text-[#484f58] cursor-not-allowed'}`}
              >
                {streaming ? '■' : '↑'}
              </button>
            </div>
            {agentMode && (
              <p className="text-[10px] text-[#484f58] mt-1 text-center">
                Agent can read / write files and run terminal commands autonomously
              </p>
            )}
          </div>
        </>
      )}
    </div>
  );
}
